# version of the docker compose
version: '3.6'

#We can have many services for example db
services:
  web:
    #build the current directory
    build: .
    command: python3 /code/manage.py runserver 0.0.0.0:8000 
    volumes:
      - .:/code
    ports:
      - 8000:8000

    depends_on:
      - db
  db:
    image: postgres:11.2-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=pollsapp
      - POSTGRES_PASSWORD=Denis1998
      - POSTGRES_DB=pollsapp_db

volumes:
  postgres_data:
