---
- hosts: servers
  vars_files:
    - vars.yml
  gather_facts: false
  become: True

  tasks:
    - name: pull project from repo
      git: repo={{ project_repo }} dest={{ install_root }}/{{ project_name }} accept_hostkey=yes force=yes


    - name: install project requirements
      pip:
        requirements: /srv/PollsApp/requirements.txt


    - name: make migrations
      shell:
        python3 /srv/PollsApp/manage.py migrate


    - name: start gunicorn
      become: True
      command: gunicorn --daemon --workers 3 --bind unix:/srv/PollsApp/mysite.sock mysite.wsgi
      args:
        chdir: /srv/PollsApp

# Enables continuous deployment
