---
- hosts: servers
  vars_files:
    - vars.yml
  gather_facts: false
  become: True

  tasks:
    - name: Clone/pull project repo
      git: repo={{ project_repo }} dest={{ install_root }}/{{ project_name }} accept_hostkey=yes force=yes


    - name: Install project requirements
      pip:
        requirements: /srv/PollsApp/requirements.txt


    - name: copy nginx config
      copy:
        src: /srv/PollsApp/files/mysite
        dest: /etc/nginx/sites-available/
        remote_src: yes


    - name: Create symbolic link
      file:
        src: /etc/nginx/sites-available/mysite
        dest: /etc/nginx/sites-enabled/mysite
        state: link


    - name: make sure nginx server is running
      service:
        name: nginx
        state: started
        enabled: yes
    
    
    - name: Make migrations
      shell:
        python3 /srv/PollsApp/manage.py migrate


    - name: start gunicorn
      become: True
      command: gunicorn --daemon --workers 3 --bind unix:/srv/PollsApp/mysite.sock mysite.wsgi
      args:
        chdir: /srv/PollsApp


    - name: restart nginx
      service:
        name: nginx
        state: restarted

- import_playbook: encrypt.yml
# vim:ft=ansible:


