---
- hosts: servers
  vars_files:
    - vars.yml
  gather_facts: false
  become: True

  tasks:
    - name: Clone/pull project repo
      git: repo={{ project_repo }} dest={{ install_root }}/{{ project_name }} accept_hostkey=yes force=yes
      notify:
      - restart gunicorn


    - name: copy nginx config
      copy:
        src: /srv/PollsApp/files/mysite
        dest: /etc/nginx/sites-available/
        remote_src: yes


    - name: Create symbolic link
      file:
        src: /etc/nginx/sites-available/mysite
        dest: /etc/nginx/sites-enabled/mysite
        state: link


    - name: make sure nginx server is running
      service:
        name: nginx
        state: started
        enabled: yes
    
    
#    - name: Make migrations
#      django_manage:
#        command: migrate
#        app_path: "{{ install_root }}/{{ project_name }}"
#        pythonpath: "{{ pythonpath }}"


    - name: start gunicorn
      become: True
      command: gunicorn --daemon --workers 3 --bind unix:/srv/PollsApp/mysite.sock mysite.wsgi
      args:
        chdir: /srv/PollsApp


  handlers: 
    - name: restart nginx
      service:
        name: nginx
        state: restarted

# vim:ft=ansible:


