---
- hosts: servers
  vars_files:
    - vars.yml
  gather_facts: false
  become: True

  tasks:
    - name: add repository for certbot
      apt_repository: 
        repo: ppa:certbot/certbot
        state: present
        update_cache: yes


    - name: install certbot
      apt: 
        name: "{{ certbot }}"


    - name: free nginx port
      service:
        name: nginx
        state: stopped
                    

    - name: enable UFW (Firewall)
      ufw:
        state: enabled


    - name: allow OpenSSH
      ufw:
        rule: allow
        name: OpenSSH


    - name: allow Nginx Full
      ufw:
        rule: allow
        name: Nginx Full
  

    - name: obtain SSL certificate
      shell: "certbot --nginx --noninteractive --agree-tos --email {{ certbot_admin_email }} -d {{ domain_1 }} -d {{ domain_2 }}"
      become: yes

- import_playbook: tick.yml
# Create secure HTTPS connection by obtaining SSL certificate
